version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - path: ./app
          target: /app/app
          action: sync
          ignore:
            - node_modules/
        - path: package.json
          action: rebuild
